modules:
  bettervanilla:
    enabled: true
  fishing:
    enabled: true
  painting:
    enabled: true
    brush-distance: 16
  economy:
    enabled: true
    # colors allowed
    # (minecraft colors) :
    #   DARK_RED, RED, GOLD, YELLOW, DARK_GREEN, GREEN, AQUA,
    #   DARK_AQUA, DARK_BLUE, BLUE, PURPLE, DARK_PURPLE, WHITE, GRAY, DARK_GRAY, BLACK
    # (custom ones) :
    #   IRIDESCENT
    # alternatively you can use RGB hex color codes : 0xFFFFFF or #FFFFFF
    # default color is WHITE
    #
    # concerning coin names : they are NOT case-sensitive, therefore Gold == GoLd == GOLD == gold
    coin-values:
      copper:
        color: WHITE
        value: 1
      iron:
        color: WHITE
        value: 5
      gold:
        color: GOLD
        value: 10
      emerald:
        color: GOLD
        value: 50
      diamond:
        color: LIGHT_BLUE
        value: 100
      netherite:
        color: DARK_PURPLE
        value: 500
      netherstar:
        color: IRIDESCENT
        value: 1000
