name: Tiboise
version: '${project.version}'
main: io.github.sawors.tiboise.Tiboise
api-version: 1.19
authors: [ Sawors ]
commands:
  tgive:
    # used to give Tiboise custom items to the player
    usage: </command> <itemname>
  tid:
    # used to give the unique identifier (as UUID) of the item in hand (if it has one)
    usage: </command> with an item in hand
  ttest:
    usage: </command> value
