name: Tiboise
version: '${project.version}'
main: io.github.sawors.tiboise.Tiboise
api-version: 1.19
authors: [ Sawors ]
load: POSTWORLD
commands:
  tgive:
    # used to give Tiboise custom items to the player
    usage: </command> <itemname>
    permission: tiboise.give
  tid:
    # used to give the unique identifier (as UUID) of the item in hand (if it has one)
    usage: </command> with an item in hand
    permission: tiboise.infos
  ttest:
    usage: </command> <action> <target>
    permission: tiboise.test
  kidnap:
    usage: </command> <player> <server>
    permission: tiboise.kidnap
  marker:
    usage: /marker [name]
  tiboise:
    aliases:
      - tb
      - t
    usage: รปwรป
  tadmin:
    usage: /tadmin [sub-command] allows you to use multiple admin utilities.
    permission: tiboise.admin
  thelp:
    usage: /thelp gives you indication on the usage of the item you have in hand.
  letter:
    usage: /letter allows you to read again the last letter you opened this session.
  sit:
    usage: /sit to sit on the block you're standing
softdepend:
  - voicechat
depend:
  - ProtocolLib

permissions:
  tiboise.kidnap:
    description: Allows you to kidnap a user
    default: op
  tiboise.give:
    description: Allows you to give items to yourself
    default: op
  tiboise.test:
    description: Allows you to use the test command
    default: op
  tiboise.admin:
    description: Allows you to use admin commands
    default: op